"""
{{SKILL_NAME}} — L2 Compute Layer
Generated by AntSkill Creator v3.0

Pipeline: Filter → Enrich → Derive → Normalize → Score → Rank → AnomalyDetect
"""
from dataclasses import dataclass, field
from typing import Optional
import math


# ─── Schemas ───────────────────────────────────────────

@dataclass
class RawProduct:
    id: str
    platform: str
    product_name: str
    apy: float
    currency: str
    venue_type: str  # "CEX" | "DeFi"
    chain: Optional[str] = None
    tvl_usd: Optional[float] = None
    lock_days: int = 0
    min_amount: Optional[float] = None
    capacity_usd: Optional[float] = None
    updated_at: str = ""


@dataclass
class ScoredProduct(RawProduct):
    tier: str = "unknown"
    audit_count: int = 0
    has_insurance: bool = False
    # Dimension scores (0-100)
    score_yield: float = 0
    score_safety: float = 0
    score_convenience: float = 0
    score_capacity: float = 0
    score_stability: float = 0
    total_score: float = 0
    rank: int = 0
    anomalies: list = field(default_factory=list)
    dims: dict = field(default_factory=dict)


@dataclass
class UserContext:
    principal_usd: float = 10000
    risk_preference: str = "balanced"  # conservative | balanced | aggressive
    convenience_requirement: str = "any"  # flexible_only | short_lock | any
    security_priority: str = "normal"  # strict | normal | relaxed


# ─── Weight Matrix ─────────────────────────────────────

WEIGHT_PRESETS = {
    # (yield, safety, convenience, capacity, stability)
    ("normal", "balanced"):     {"yield": 0.30, "safety": 0.25, "convenience": 0.20, "capacity": 0.10, "stability": 0.15},
    ("strict", "balanced"):     {"yield": 0.20, "safety": 0.40, "convenience": 0.15, "capacity": 0.10, "stability": 0.15},
    ("normal", "aggressive"):   {"yield": 0.45, "safety": 0.15, "convenience": 0.15, "capacity": 0.10, "stability": 0.15},
    ("strict", "conservative"): {"yield": 0.15, "safety": 0.40, "convenience": 0.20, "capacity": 0.10, "stability": 0.15},
}


def get_weights(user: UserContext) -> dict:
    key = (user.security_priority, user.risk_preference)
    return WEIGHT_PRESETS.get(key, WEIGHT_PRESETS[("normal", "balanced")])


# ─── Step 1: Filter ───────────────────────────────────

def filter_products(products: list[RawProduct], user: UserContext) -> list[RawProduct]:
    result = []
    for p in products:
        # F1: Currency filter — only stablecoins
        # {{Customize filter rules}}
        
        # F2: Convenience filter
        if user.convenience_requirement == "flexible_only" and p.lock_days > 0:
            continue
        if user.convenience_requirement == "short_lock" and p.lock_days > 30:
            continue
        
        result.append(p)
    return result


# ─── Step 2: Enrich ───────────────────────────────────

def enrich(products: list[RawProduct], platform_meta: dict) -> list[ScoredProduct]:
    enriched = []
    for p in products:
        sp = ScoredProduct(**p.__dict__)
        meta = platform_meta.get(p.platform, {})
        sp.tier = meta.get("tier", "unknown")
        sp.audit_count = meta.get("audit_count", 0)
        sp.has_insurance = meta.get("has_insurance", False)
        enriched.append(sp)
    return enriched


# ─── Step 3: Derive ───────────────────────────────────

def derive(products: list[ScoredProduct], history: dict = None) -> list[ScoredProduct]:
    """Add derived fields (e.g., 30d volatility). Extend as needed."""
    # {{Add derived computations here}}
    return products


# ─── Step 4: Normalize ────────────────────────────────

def normalize(value: float, min_val: float, max_val: float, invert: bool = False) -> float:
    if max_val == min_val:
        return 50.0
    score = (value - min_val) / (max_val - min_val) * 100
    score = max(0.0, min(100.0, score))
    return (100.0 - score) if invert else score


# ─── Step 5: Score ─────────────────────────────────────

def calc_safety(p: ScoredProduct) -> float:
    score = 0
    tier_scores = {"Tier-1": 40, "Tier-2": 25, "Tier-3": 10, "unknown": 0}
    score += tier_scores.get(p.tier, 0)
    score += min(p.audit_count * 8, 25)
    if p.has_insurance:
        score += 10
    # {{Add more safety factors}}
    return min(score, 100)


def score_products(products: list[ScoredProduct], user: UserContext) -> list[ScoredProduct]:
    weights = get_weights(user)
    
    # Collect ranges for normalization
    apys = [p.apy for p in products] or [0]
    locks = [p.lock_days for p in products] or [0]
    caps = [p.capacity_usd or 0 for p in products] or [0]
    
    for p in products:
        p.score_yield = normalize(p.apy, 0, max(apys) * 1.2)
        p.score_safety = calc_safety(p)
        p.score_convenience = normalize(p.lock_days, 0, max(max(locks), 365), invert=True)
        p.score_capacity = normalize(p.capacity_usd or 0, 0, max(max(caps), 1))
        p.score_stability = 50  # {{Replace with real 30d vol calculation}}
        
        p.dims = {
            "yield": p.score_yield,
            "safety": p.score_safety,
            "convenience": p.score_convenience,
            "capacity": p.score_capacity,
            "stability": p.score_stability,
        }
        p.total_score = sum(p.dims[k] * weights[k] for k in p.dims)
    
    return products


# ─── Step 6: Rank ──────────────────────────────────────

def rank_products(products: list[ScoredProduct]) -> list[ScoredProduct]:
    products.sort(key=lambda p: (-p.total_score, -p.score_safety))
    for i, p in enumerate(products):
        p.rank = i + 1
    return products


# ─── Step 7: Anomaly Detect ───────────────────────────

ANOMALY_RULES = [
    {
        "name": "YIELD_OUTLIER",
        "check": lambda p, stats: p.apy > stats["mean"] + 3 * stats["std"],
        "severity": "warning",
    },
    # {{Add more rules}}
]


def detect_anomalies(products: list[ScoredProduct]) -> list[ScoredProduct]:
    apys = [p.apy for p in products]
    if len(apys) < 2:
        return products
    
    mean_apy = sum(apys) / len(apys)
    std_apy = (sum((a - mean_apy) ** 2 for a in apys) / len(apys)) ** 0.5
    stats = {"mean": mean_apy, "std": std_apy}
    
    for p in products:
        for rule in ANOMALY_RULES:
            try:
                if rule["check"](p, stats):
                    p.anomalies.append(rule["name"])
            except Exception:
                pass
    return products


# ─── Pipeline Entry Point ─────────────────────────────

def run(raw_products: list[RawProduct], user: UserContext, platform_meta: dict, history: dict = None) -> dict:
    """Full L2 pipeline. Returns dict for L3 consumption."""
    filtered = filter_products(raw_products, user)
    enriched = enrich(filtered, platform_meta)
    derived = derive(enriched, history)
    scored = score_products(derived, user)
    ranked = rank_products(scored)
    final = detect_anomalies(ranked)
    
    apys = [p.apy for p in final] or [0]
    market_stats = {
        "median_apy": sorted(apys)[len(apys) // 2] if apys else 0,
        "mean_apy": sum(apys) / len(apys) if apys else 0,
        "product_count": len(final),
    }
    
    anomaly_alerts = [
        {"product_id": p.id, "rule_name": a, "severity": "warning"}
        for p in final for a in p.anomalies
    ]
    
    return {
        "scored_products": [p.__dict__ for p in final],
        "market_stats": market_stats,
        "anomaly_alerts": anomaly_alerts,
    }
