"""
{{SKILL_NAME}} — L3 Decision Layer
Generated by AntSkill Creator v3.0

Responsibilities: LLM call → structured JSON output → fallback
"""
import json
import os

# ─── Config ────────────────────────────────────────────

MODEL = "claude-sonnet-4-20250514"
MAX_TOKENS = 1000
TEMPERATURE = 0.3

SYSTEM_PROMPT = """
# Role
你是{{角色名}}，专注于{{领域}}。

# Input
你会收到一个 JSON 对象，包含: user_context, market_stats, scored_products, anomaly_alerts。

# Output
严格返回以下 JSON，不要包含任何 Markdown 或额外文字：

{
  "headline": "不超过 40 字的核心结论",
  "top1_reason": "80-120 字，解释为什么 TOP 1 最优",
  "opportunity_cost": "包含金额对比的机会成本分析",
  "risk_warning": "至少 40 字的风险提示",
  "anomaly_narratives": ["异常 1 的人话解释"],
  "brief_for_card": [
    {"rank": 1, "one_liner": "一句话点评"}
  ]
}

# Writing Rules
1. 首句即结论 — headline 第一个词必须是平台名或关键数字
2. 金字塔结构 — 结论 > 论据 > 细节
3. 风险对称 — 推荐了什么就必须在 risk_warning 中提及对应风险
4. 机会成本 — 必须包含"如果选 X 而不选 Y，每年差 $Z"的对比
5. 异常叙事 — 把 anomaly_alerts 翻译成人话，含具体数字
6. 禁止 — 不含"我认为"、"我觉得"、"我建议"
""".strip()


# ─── LLM Call ──────────────────────────────────────────

def call_llm(l2_output: dict, user_context: dict) -> dict:
    """
    Call Anthropic API. Returns parsed JSON or raises.
    In production, this should go through a backend proxy.
    """
    import urllib.request
    
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise EnvironmentError("ANTHROPIC_API_KEY not set")
    
    payload = {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "temperature": TEMPERATURE,
        "system": SYSTEM_PROMPT,
        "messages": [
            {
                "role": "user",
                "content": json.dumps({
                    "user_context": user_context,
                    "market_stats": l2_output["market_stats"],
                    "scored_products": l2_output["scored_products"][:5],
                    "anomaly_alerts": l2_output["anomaly_alerts"],
                }, ensure_ascii=False)
            }
        ]
    }
    
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        }
    )
    
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read())
    
    # Extract text from response
    text = ""
    for block in data.get("content", []):
        if block.get("type") == "text":
            text += block["text"]
    
    # Clean and parse
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()
    
    return json.loads(text)


# ─── Fallback ──────────────────────────────────────────

def fallback_decision(l2_output: dict, user_context: dict) -> dict:
    """Template-based fallback when LLM is unavailable."""
    products = l2_output.get("scored_products", [])
    stats = l2_output.get("market_stats", {})
    principal = user_context.get("principal_usd", 10000)
    
    if not products:
        return {
            "headline": "暂无符合条件的产品",
            "top1_reason": "当前筛选条件下没有找到合适的产品，建议放宽筛选条件后重试。",
            "opportunity_cost": "",
            "risk_warning": "以上分析基于历史数据和公开信息，不构成投资建议。请自行评估风险。",
            "anomaly_narratives": [],
            "brief_for_card": [],
        }
    
    top1 = products[0]
    annual = principal * top1.get("apy", 0)
    median_annual = principal * stats.get("median_apy", 0)
    
    return {
        "headline": f"综合评分最高: {top1['platform']} {top1['product_name']}",
        "top1_reason": (
            f"{top1['platform']} 的 {top1['product_name']} "
            f"在 {len(products)} 个产品中综合评分第一 "
            f"(评分 {top1.get('total_score', 0):.0f}/100)，"
            f"年化收益率 {top1.get('apy', 0)*100:.1f}%。"
        ),
        "opportunity_cost": (
            f"按 ${principal:,.0f} 本金计算，"
            f"选择 TOP 1 年收益约 ${annual:,.0f}，"
            f"比市场中位数多 ${annual - median_annual:,.0f}。"
        ),
        "risk_warning": "以上分析基于历史数据和公开信息，不构成投资建议。收益率可能随市场变化，请自行评估风险。",
        "anomaly_narratives": [],
        "brief_for_card": [
            {"rank": i + 1, "one_liner": f"综合评分 {p.get('total_score', 0):.0f}/100，APY {p.get('apy', 0)*100:.1f}%"}
            for i, p in enumerate(products[:3])
        ],
    }


# ─── Entry Point ───────────────────────────────────────

def run(l2_output: dict, user_context: dict) -> dict:
    """Run L3: try LLM, fall back to template."""
    try:
        return call_llm(l2_output, user_context)
    except Exception as e:
        print(f"[L3] LLM failed ({e}), using fallback")
        return fallback_decision(l2_output, user_context)
