"""
{{SKILL_NAME}} — Pipeline Orchestrator
Generated by AntSkill Creator v3.0

Orchestrates L1 → L2 → L3 → L4 pipeline.
"""
import json
import time


def run_pipeline(user_input: dict) -> dict:
    """
    Full pipeline execution.
    
    Args:
        user_input: {
            "principal_usd": 10000,
            "risk_preference": "balanced",
            "convenience_requirement": "any",
            "security_priority": "normal"
        }
    
    Returns:
        Complete output dict for L4 rendering.
    """
    timings = {}
    
    # ─── Phase 1: L1 Data ──────────────────────────
    t0 = time.time()
    # from pipeline.l1_data.fetcher import fetch_all
    # raw_products = fetch_all()
    raw_products = []  # {{Replace with real L1 call}}
    timings["l1_data"] = time.time() - t0
    
    # ─── Phase 2: L2 Compute ───────────────────────
    t0 = time.time()
    # from pipeline.l2_compute.compute import run as l2_run
    # from pipeline.l2_compute.compute import UserContext
    # user_ctx = UserContext(**user_input)
    # l2_output = l2_run(raw_products, user_ctx, platform_meta)
    l2_output = {
        "scored_products": [],
        "market_stats": {},
        "anomaly_alerts": [],
    }  # {{Replace with real L2 call}}
    timings["l2_compute"] = time.time() - t0
    
    # ─── Phase 3: L3 Decision ──────────────────────
    t0 = time.time()
    # from pipeline.l3_decision.decision import run as l3_run
    # l3_output = l3_run(l2_output, user_input)
    l3_output = {
        "headline": "",
        "top1_reason": "",
        "opportunity_cost": "",
        "risk_warning": "",
        "anomaly_narratives": [],
        "brief_for_card": [],
    }  # {{Replace with real L3 call}}
    timings["l3_decision"] = time.time() - t0
    
    # ─── Phase 4: Assemble for L4 ─────────────────
    result = {
        "user_input": user_input,
        "l2": l2_output,
        "l3": l3_output,
        "meta": {
            "timings": timings,
            "total_time": sum(timings.values()),
            "product_count": len(l2_output.get("scored_products", [])),
        }
    }
    
    return result


if __name__ == "__main__":
    # Example run
    output = run_pipeline({
        "principal_usd": 50000,
        "risk_preference": "balanced",
        "convenience_requirement": "flexible_only",
        "security_priority": "normal",
    })
    print(json.dumps(output, indent=2, ensure_ascii=False))
